print("Enter any four numbers")
print("It will evaluate (x1 + x2)/(x3 + x4)")
print("Shall we start?")
number1 = float(input("Enter the first number:"))
number2 = float(input("Enter the second number:"))
number3 = float(input("Enter the third number:"))
number4 = float(input("Enter the fourth number:"))
print("Your answer:")
print("%.2f" %((number1 + number2) / (number3 + number4)))